### ISSUE TITLE
What is the accuracy of this repo on the Mini-ImageNet dataset?

### ISSUE THREAD

**Issue by zhangyikaii** [jakesnell/prototypical-networks#21]
For example, the Setup is `1-Shot 5-Way` or something. the backbone is `ResNet-12` or something.
Thank you very much.

**Comment by zxkplus** [comment]
I am trying to reproduced this parper on MiniIamgeNet, and get some results. I use this origin code and build the Mini ImageNet dataset code  by imitated the Omniglot code and spilt it based on ravi's csv file. but the results that I get are better than author's , that confused me. did you get some results about the Mini ImageNet?

**Comment by ZhangYikaii** [comment]
@zxkplus Can I get in touch with you to discuss some implementation details? My email is `zykycy@gmail.com`.

**Comment by zxkplus** [comment]
Hi , I had send a email to you , but did not replied.

**Comment by ZhangYikaii** [comment]
Actually, I didn't get it, can you add my WeChat `YikaiZhang_`?

**Comment by zhang1hongliang** [comment]
@zxkplus , I can only use this origin code to test Omniglot dataset, I need to test the improved version on the Mini ImageNet dataset. Can you send me the Mini ImageNet dataset code that you have built, my email zhang1hongliang@163.com, thank you very much.
